blog_comment:
    resource: "@BlogBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

index:
    path:     /
    defaults: { _controller: BlogBundle:Page:index }

contacts:
    path:     /contacts
    defaults: { _controller: BlogBundle:Page:contacts }

about:
    path:     /about
    defaults: { _controller: BlogBundle:Page:about }

item:
    path:     /news/{id}
    defaults: { _controller: BlogBundle:News:item }
