BlogBundle\Entity\News:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\NewsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        content:
            type: text
            length: 65535
        createdAt:
            type: datetime
            column: created_at
        categoryId:
            type: integer
            column: category_id
    lifecycleCallbacks: {  }

    manyToOne:
        categories:
            targetEntity: Category
            inversedBy: news
            joinColumn:
                name: category_id
                referencedColumnName: id
